--- 
language: cpp
compiler: 
- clang
- gcc

env: 
  matrix: 
  - BUILDTOOL=autotools
  - BUILDTOOL=cmake
  - BUILDTOOL=autotools_old_compilers

install: 
- git submodule update
- cd cpputest
- cmake CMakeLists.txt
- make
- cp -r /usr/local/lib ./
- cp -r /usr/local/include/CppUTest ./include
- cp -r /usr/local/include/CppUTestExt ./include
script: cd ../test/; make
