--- 
language: cpp
compiler: 
- clang
- gcc

env: 
  matrix: 
  - BUILDTOOL=cmake

install: 
- git submodule update
- cd cpputest
- mkdir ./lib
- export LD_LIBRARY_PATH=./lib
- cmake CMakeLists.txt
- make

script: cd ../test/; make
