--- 
language: cpp
compiler: 
- clang
- gcc

env: 
  matrix: 
  - BUILDTOOL=autotools
  - BUILDTOOL=cmake
  - BUILDTOOL=autotools_old_compilers

install: 
- git submodule update
- cd cpputest
- cmake CMakeList.txt
- make
script: cd test/; make
