--- 
language: cpp
compiler: 
- clang
- gcc

env: 
  matrix: 
  - BUILDTOOL=cmake

install: 
- git submodule update
- cd cpputest
- cmake -DCMAKE_INSTALL_PREFIX = ./
- cmake CMakeLists.txt
- make

script: cd ../test/; make
