--- 
language: cpp
compiler: 
- clang
- gcc

env: 
  matrix: 
  - BUILDTOOL=autotools
  - BUILDTOOL=cmake
  - BUILDTOOL=autotools_old_compilers

install: 
- git submodule update
- cd cpputest
- cmake CMakeLists.txt
- make
- mkdir lib
- cp -r /usr/local/lib ./lib

script: cd ../test/; make
