--- 
language: cpp
compiler: 
- clang
- gcc

env: 
  matrix: 
  - BUILDTOOL=autotools
  - BUILDTOOL=cmake
  - BUILDTOOL=autotools_old_compilers

install: 

- git submodule update
- cd cpputest
- export LD_LIBRARY_PATH=./lib
- cmake CMakeLists.txt
- make

script: cd ../test/; make
